plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.compose.compiler)
}

val appVersionName = libs.versions.app.versionName.get()
val wearVersionCode = libs.versions.app.wearVersionCode.get().toInt()

val buildInfoDir = layout.buildDirectory.dir("generated/source/buildInfo/main/kotlin")

val generateWearBuildInfo = tasks.register("generateWearBuildInfo") {
    inputs.property("versionName", appVersionName)
    inputs.property("versionCode", wearVersionCode)
    outputs.dir(buildInfoDir)

    doLast {
        val file = buildInfoDir.get().file("com/kiblatsaya/app/wear/core/WearBuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.kiblatsaya.app.wear.core

            /**
             * Automatically generated by Gradle build task. Do not edit manually.
             */
            object WearBuildInfo {
                const val VERSION_NAME = "$appVersionName"
                const val VERSION_CODE = $wearVersionCode
                const val VERSION_DISPLAY = "v$appVersionName"
            }
            """.trimIndent()
        )
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateWearBuildInfo)
}

android {
    namespace = "com.kiblatsaya.app.wear"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.kiblatsaya.app"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = wearVersionCode
        versionName = appVersionName
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        getByName("main") {
            kotlin.srcDirs(
                "src/main/kotlin",
                "../composeApp/src/commonMain/kotlin/com/kiblatsaya/app/domain/qibla",
                buildInfoDir
            )
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    signingConfigs {
        create("release") {
            storeFile = file("../composeApp/kiblatsaya-release.jks")
            storePassword = System.getenv("KEYSTORE_PASSWORD") ?: "kiblatsaya2026"
            keyAlias = System.getenv("KEY_ALIAS") ?: "kiblatsaya"
            keyPassword = System.getenv("KEY_PASSWORD") ?: "kiblatsaya2026"
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.lifecycle.runtime.compose)

    implementation(libs.wear.compose.material)
    implementation(libs.wear.compose.foundation)
    implementation(libs.wear.compose.ui.tooling)
    implementation(libs.wear.tooling.preview)
    implementation(libs.play.services.wearable)

    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)

    implementation(libs.multiplatform.settings)
    implementation(libs.multiplatform.settings.no.arg)
}

val distDir = rootProject.file("dist")

tasks.register<Copy>("copyWearReleaseArtifactsToDist") {
    dependsOn("bundleRelease", "assembleRelease")
    from(layout.buildDirectory.file("outputs/bundle/release/wearApp-release.aab")) {
        rename { "KiblatSaya-WearOS-v$appVersionName.aab" }
    }
    from(layout.buildDirectory.file("outputs/apk/release/wearApp-release.apk")) {
        rename { "KiblatSaya-WearOS-v$appVersionName.apk" }
    }
    into(distDir)
}

tasks.register<Copy>("copyWearDebugArtifactsToDist") {
    dependsOn("assembleDebug")
    from(layout.buildDirectory.file("outputs/apk/debug/wearApp-debug.apk")) {
        rename { "KiblatSaya-WearOS-v$appVersionName-debug.apk" }
    }
    into(distDir)
}

tasks.register("distributeRelease") {
    group = "distribution"
    description = "Builds Wear OS release APK and AAB and copies them to dist/."
    dependsOn("copyWearReleaseArtifactsToDist")
}

tasks.register("distributeDebug") {
    group = "distribution"
    description = "Builds Wear OS debug APK and copies it to dist/."
    dependsOn("copyWearDebugArtifactsToDist")
}
