import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

val appVersionName = libs.versions.app.versionName.get()
val appVersionCode = libs.versions.app.versionCode.get().toInt()

val generateAppBuildInfo = tasks.register("generateAppBuildInfo") {
    val outputDir = layout.buildDirectory.dir("generated/source/buildInfo/commonMain/kotlin")
    inputs.property("versionName", appVersionName)
    inputs.property("versionCode", appVersionCode)
    outputs.dir(outputDir)

    doLast {
        val file = outputDir.get().file("com/kiblatsaya/app/core/AppBuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.kiblatsaya.app.core

            /**
             * Automatically generated by Gradle build task from gradle/libs.versions.toml.
             * Do not edit manually.
             */
            object AppBuildInfo {
                const val VERSION_NAME = "$appVersionName"
                const val VERSION_CODE = $appVersionCode
                const val VERSION_DISPLAY = "v$appVersionName"
            }
            """.trimIndent()
        )
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain.configure {
            kotlin.srcDir(generateAppBuildInfo)
        }
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.core.ktx)
            implementation(libs.kotlinx.coroutines.android)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(compose.materialIconsExtended)

            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)

            implementation(libs.kotlinx.coroutines.core)

            implementation(libs.multiplatform.settings)
            implementation(libs.multiplatform.settings.no.arg)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

android {
    namespace = "com.kiblatsaya.app"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.kiblatsaya.app"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = appVersionCode
        versionName = appVersionName
    }

    signingConfigs {
        create("release") {
            storeFile = file("kiblatsaya-release.jks")
            storePassword = System.getenv("KEYSTORE_PASSWORD") ?: "kiblatsaya2026"
            keyAlias = System.getenv("KEY_ALIAS") ?: "kiblatsaya"
            keyPassword = System.getenv("KEY_PASSWORD") ?: "kiblatsaya2026"
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

val distDir = rootProject.file("dist")

tasks.register<Copy>("copyReleaseArtifactsToDist") {
    dependsOn("bundleRelease", "assembleRelease")
    from(layout.buildDirectory.file("outputs/bundle/release/composeApp-release.aab")) {
        rename { "KiblatSaya-v$appVersionName.aab" }
    }
    from(layout.buildDirectory.file("outputs/apk/release/composeApp-release-unsigned.apk")) {
        rename { "KiblatSaya-v$appVersionName.apk" }
    }
    from(layout.buildDirectory.file("outputs/apk/release/composeApp-release.apk")) {
        rename { "KiblatSaya-v$appVersionName.apk" }
    }
    into(distDir)
}

tasks.register<Copy>("copyDebugArtifactsToDist") {
    dependsOn("assembleDebug")
    from(layout.buildDirectory.file("outputs/apk/debug/composeApp-debug.apk")) {
        rename { "KiblatSaya-v$appVersionName-debug.apk" }
    }
    into(distDir)
}

tasks.register("distributeRelease") {
    group = "distribution"
    description = "Builds release APK and AAB and copies them into root dist/ directory."
    dependsOn("copyReleaseArtifactsToDist")
}

tasks.register("distributeDebug") {
    group = "distribution"
    description = "Builds debug APK and copies it into root dist/ directory."
    dependsOn("copyDebugArtifactsToDist")
}
